---

- name: include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # artixlinux-openrc
        - "{{ ansible_distribution | lower | replace(' ', '') }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        - default.yml
      skip: true

- name: debian
  when:
    - ansible_os_family | lower == 'debian'
  block:
    - name: add rspamd repo GPG key
      ansible.builtin.apt_key:
        url: https://rspamd.com/apt-stable/gpg.key

    # Use of the distribution packages is discouraged by the rspamd devs
    - name: add official rspamd repository
      ansible.builtin.apt_repository:
        repo: deb http://rspamd.com/apt-stable/ {{ ansible_distribution_release }} main
        filename: rspamd

- name: redhat
  when:
    - ansible_os_family | lower == 'redhat'
  block:
    - name: import EPEL GPG key
      ansible.builtin.rpm_key:
        key: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present

    - name: install EPEL repository
      ansible.builtin.yum_repository:
        name: epel
        state: present
        description: Extra Packages for Enterprise Linux {{ ansible_distribution_major_version }} - $basearch
        baseurl: http://download.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/$basearch
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-{{ ansible_distribution_major_version }}&arch=$basearch&infra=$infra&content=$contentdir
        failovermethod: priority
        gpgcheck: 1
        enabled: 1

    - name: import rspamd GPG key
      ansible.builtin.rpm_key:
        key: https://rspamd.com/rpm-stable/gpg.key
        state: present

    - name: install rspamd repository
      ansible.builtin.get_url:
        url: https://rspamd.com/rpm-stable/centos-{{ ansible_distribution_major_version }}/rspamd.repo
        dest: /etc/yum.repos.d/rspamd.repo
        mode: 0660
      register: download_artefact
      until: download_artefact is succeeded
      retries: 5
      delay: 2

    - name: update rpm cache (yum) # noqa 'command-instead-of-module'
      ansible.builtin.command: yum clean metadata
      args:
        warn: false
      when:
        - ansible_distribution_major_version | int == 7

    - name: update rpm cache (dnf) # noqa 'command-instead-of-module'
      ansible.builtin.command: dnf clean metadata
      args:
        warn: false
      when:
        - ansible_distribution_major_version | int >= 8

- name: update package cache
  ansible.builtin.package:
    update_cache: true

- name: merge dovecot configuration between defaults and custom
  ansible.builtin.set_fact:
    rspamd_logging: "{{ rspamd_defaults_logging | combine(rspamd_logging, recursive=True) }}"
    rspamd_workers: "{{ rspamd_defaults_workers | combine(rspamd_workers, recursive=True) }}"
    rspamd_redis: "{{ rspamd_defaults_redis | combine(rspamd_redis, recursive=True) }}"
    rspamd_local_config: "{{ rspamd_defaults_local_config | combine(rspamd_local_config, recursive=True) }}"
    rspamd_config_overrides: "{{ rspamd_defaults_config_overrides | combine(rspamd_config_overrides, recursive=True) }}"

...
