---

- name: enable rspamd services
  ansible.builtin.service:
    name: rspamd
    enabled: true

- name: ensure rspamd service are started
  ansible.builtin.service:
    name: rspamd
    state: started

...
