---

rspamd_logging:
  ## type                    Defines logging type (file, console or syslog). For some types mandatory attributes may be required.
  type: console
  ## systemd                 If true timestamps aren’t prepended to log messages. Default: false.
  systemd: true
  ## filename                Path to log file for file logging (required for file type)
  ## facility                Logging facility for syslog type (required if this type is used)
  ## level                   Defines logging level (error, warning, info or debug).
  level: info
  ## log_buffered            Flag that controls whether logging is buffered.
  ## log_buf_size            For file and console logging defines buffer size that will be used for logging output.
  ## log_urls                Flag that defines whether all URLs in message should be logged. Useful for testing. Default: false.
  ## log_re_cache            Output regular expressions statistics after each message. Default: true.
  ## debug_ip                List that contains IP addresses for which debugging should be turned on.
  ## color                   Turn on coloring for log messages. Default: false.
  ## debug_modules           A list of modules that are enabled for debugging.
  ## log_usec                Log microseconds (e.g. 11:43:16.68071). Default: false.
  ## log_severity (2.8+)     Log severity explicitly (e.g. [info] or [error]). Default: false


rspamd_local_config:
  groups:
    group:
      informational:
        description: Informational (non-weighted) symbols
        max_score: 0.0
        symbols:
          ASN:
            description: Network information of the source host
          MAILLIST:
            description: Name of the mailing list software
  actions:
    reject: 15
    add_header: 8
    greylist: 7
  dkim_signing:
    # If false, messages with empty envelope from are not signed
    allow_envfrom_empty: true
    # If true, envelope/header domain mismatch is ignored
    allow_hdrfrom_mismatch: true
    # If true, multiple from headers are allowed (but only first is used)
    allow_hdrfrom_multiple: true
    # If true, username does not need to contain matching domain
    allow_username_mismatch: true
    # If false, messages from authenticated users are not selected for signing
    sign_authenticated: true
    # Default path to key, can include '$domain' and '$selector' variables
    path: "/data/dkim/keys/$domain.dkim"
    # Default selector to use
    selector: "dkim"
    # If false, messages from local networks are not selected for signing
    sign_local: true
    # Symbol to add when message is signed
    symbol: "DKIM_SIGNED"
    # Whether to fallback to global config
    try_fallback: true
    # Domain to use for DKIM signing: can be "header" or "envelope"
    use_domain: "envelope"
    # Whether to normalise domains to eSLD
    use_esld: false
    # Whether to get keys from Redis
    use_redis: true
    # Hash for DKIM keys in Redis
    key_prefix: "DKIM_PRIV_KEYS"
    # Selector map
    selector_prefix: "DKIM_SELECTORS"
    # Sieve is in sign_networks only
    # forwards are arc signed, rejects are dkim signed
    sign_networks: "/etc/rspamd/custom/dovecot_trusted.map"
    use_domain_sign_networks: "header"
    sign_headers: "from:sender:reply-to:subject:date:message-id:to:cc:mime-version:content-type:content-transfer-encoding:content-language:resent-to:resent-cc:resent-from:resent-sender:resent-message-id:in-reply-to:references:list-id:list-help:list-owner:list-unsubscribe:list-subscribe:list-post:list-unsubscribe-post:disposition-notification-to:disposition-notification-options:original-recipient:openpgp:autocrypt"
  mx_check:
    timeout: 8.0
    symbol_bad_mx: "MX_INVALID"
    symbol_no_mx: "MX_MISSING"
    symbol_good_mx: "MX_GOOD"
    expire: 86400
    key_prefix: "rmx"
    enabled: true

rspamd_config_overrides:
  redis:
    servers: "127.0.0.1,redis"
  options:
    neighbours:
      # The controller workers are proxied by nginx with TLS and basic auth
      spam01:
        host: https://127.0.0.1:443
      spam02:
        host: https://192.168.178.5:443

# https://rspamd.com/doc/workers/
rspamd_workers:
  ## normal: this worker is designed to scan mail messages
  normal:
    options:
      ## bind_socket - a string that defines bind address of a worker. If the port number is omitted, port 11333 is assumed.
      ## count - number of worker instances to run (some workers ignore that option, e.g. hs_helper)
      ## enabled (1.6.2+) - a Boolean (true or false), enable or disable a worker (true by default)
      bind_socket: localhost:11333
      ## mime: turn to false if you want to scan non-mime messages (e.g. forum comments or SMS), default: true
      ## allow_learn: turn to true if you want to learn messages using this worker (usually you should use controller worker), default: false
      ## timeout: input/output timeout, default: 1min
      ## task_timeout: maximum time to process a single task, default: 8s
      ## max_tasks: maximum count of tasks processes simultaneously, default: 0 - no limit
      ## keypair: encryption keypair

  ## rspamd_proxy: handles requests forwarding and milter protocol
  rspamd_proxy:
    options:
      ## bind_socket - a string that defines bind address of a worker. If the port number is omitted, port 11333 is assumed.
      ## count - number of worker instances to run (some workers ignore that option, e.g. hs_helper)
      ## enabled (1.6.2+) - a Boolean (true or false), enable or disable a worker (true by default)
      bind_socket: localhost:11332

  ## controller: this worker performs configuration actions, such as learning, adding fuzzy hashes and serving web interface requests
  controller:
    options:
      ## bind_socket - a string that defines bind address of a worker. If the port number is omitted, port 11333 is assumed.
      ## count - number of worker instances to run (some workers ignore that option, e.g. hs_helper)
      ## enabled (1.6.2+) - a Boolean (true or false), enable or disable a worker (true by default)
      bind_socket: localhost:11334
      ## password: password for read-only commands
      ## enable_password: password for write commands
      ## secure_ip: list or map with IP addresses that are treated as secure so all commands are allowed from these IPs without passwords (if a reverse proxy sets an X-Forwarded-For header, both the proxy and actual client IP must be contained in secure_ip)
      ## static_dir: directory where interface static files are placed (usually ${WWWDIR})
      ## stats_path: path where controller save persistent stats about rspamd (such as scanned messages count)
      ## bind_socket : a string that defines bind address of a worker-controller (web interface). If the port number is omitted, port 11334 is assumed (see also the common workers options)

  ## fuzzy_storage: stores fuzzy hashes
  fuzzy:
    options:
      ## bind_socket - a string that defines bind address of a worker. If the port number is omitted, port 11333 is assumed.
      ## count - number of worker instances to run (some workers ignore that option, e.g. hs_helper)
      ## enabled (1.6.2+) - a Boolean (true or false), enable or disable a worker (true by default)
      bind_socket: localhost:11335
      count: -1
      ## hashfile - path to the sqlite storage (where are also few outdated aliases for this command exist: hash_file, file, database)
      ## backend - set it to redis if you want to use a redis server
      ## sync - time to perform database sync in seconds, default value: 60
      ## expire - time value for hashes expiration in seconds, default value: 2 days
      ## keypair - encryption keypair (can be repeated for different keys), can be obtained via rspamadm keypair -u command
      ## keypair_cache_size - Size of keypairs cache, default value: 512
      ## encrypted_only - allow encrypted requests only (and forbid all unknown keys or plaintext requests)
      ## master_timeout - master protocol IO timeout
      ## sync_keypair - encryption key for master/slave updates
      ## masters - string, allow master/slave updates from the following IP addresses
      ## master_key - allow master/slave updates merely using the specified key
      ## slave - list of slave hosts.
      ## mirror - list of slave hosts, same as slave
      ## allow_update - string, array of strings or a map of IP addresses that are allowed to perform changes to fuzzy storage (you should also set read_only = no in your fuzzy_check plugin

  ## lua: runs custom Lua scripts
  lua: {}

...
